=== 6870064/BaseTestFramework/src/schemas/User_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1699656152.json",
  "title": "Root",
  "type": "object",
  "required": [
    "id",
    "title",
    "firstName",
    "lastName",
    "picture",
    "gender",
    "email",
    "dateOfBirth",
    "phone",
    "location",
    "registerDate",
    "updatedDate"
  ],
  "properties": {
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": "",
      "examples": [
        "60d0fe4f5311236168a109dd"
      ],
      "pattern": "^.*$"
    },
    "title": {
      "$id": "#root/title",
      "title": "Title",
      "type": "string",
      "default": "",
      "examples": [
        "mr"
      ],
      "pattern": "^.*$"
    },
    "firstName": {
      "$id": "#root/firstName",
      "title": "Firstname",
      "type": "string",
      "default": "",
      "examples": [
        "Miguel"
      ],
      "pattern": "^.*$"
    },
    "lastName": {
      "$id": "#root/lastName",
      "title": "Lastname",
      "type": "string",
      "default": "",
      "examples": [
        "Lima"
      ],
      "pattern": "^.*$"
    },
    "picture": {
      "$id": "#root/picture",
      "title": "Picture",
      "type": "string",
      "default": "",
      "examples": [
        "https://randomuser.me/api/portraits/med/men/31.jpg"
      ],
      "pattern": "^.*$"
    },
    "gender": {
      "$id": "#root/gender",
      "title": "Gender",
      "type": "string",
      "default": "",
      "examples": [
        "male"
      ],
      "pattern": "^.*$"
    },
    "email": {
      "$id": "#root/email",
      "title": "Email",
      "type": "string",
      "default": "",
      "examples": [
        "miguel.lima@example.com"
      ],
      "pattern": "^.*$"
    },
    "dateOfBirth": {
      "$id": "#root/dateOfBirth",
      "title": "Dateofbirth",
      "type": "string",
      "default": "",
      "examples": [
        "1979-07-05T22:21:32.623Z"
      ],
      "pattern": "^.*$"
    },
    "phone": {
      "$id": "#root/phone",
      "title": "Phone",
      "type": "string",
      "default": "",
      "examples": [
        "(33) 1399-0495"
      ],
      "pattern": "^.*$"
    },
    "location": {
      "$id": "#root/location",
      "title": "Location",
      "type": "object",
      "required": [
        "street",
        "city",
        "state",
        "country",
        "timezone"
      ],
      "properties": {
        "street": {
          "$id": "#root/location/street",
          "title": "Street",
          "type": "string",
          "default": "",
          "examples": [
            "9637, Rua Rio de Janeiro "
          ],
          "pattern": "^.*$"
        },
        "city": {
          "$id": "#root/location/city",
          "title": "City",
          "type": "string",
          "default": "",
          "examples": [
            "Cascavel"
          ],
          "pattern": "^.*$"
        },
        "state": {
          "$id": "#root/location/state",
          "title": "State",
          "type": "string",
          "default": "",
          "examples": [
            "AmapÃ¡"
          ],
          "pattern": "^.*$"
        },
        "country": {
          "$id": "#root/location/country",
          "title": "Country",
          "type": "string",
          "default": "",
          "examples": [
            "Brazil"
          ],
          "pattern": "^.*$"
        },
        "timezone": {
          "$id": "#root/location/timezone",
          "title": "Timezone",
          "type": "string",
          "default": "",
          "examples": [
            "+4:00"
          ],
          "pattern": "^.*$"
        }
      }
    }
  ,
    "registerDate": {
      "$id": "#root/registerDate",
      "title": "Registerdate",
      "type": "string",
      "default": "",
      "examples": [
        "2021-06-21T21:02:10.647Z"
      ],
      "pattern": "^.*$"
    },
    "updatedDate": {
      "$id": "#root/updatedDate",
      "title": "Updateddate",
      "type": "string",
      "default": "",
      "examples": [
        "2021-06-21T21:02:10.647Z"
      ],
      "pattern": "^.*$"
    }
  }
}

=== 6870064/BaseTestFramework/src/test/resources/json_files/one_user_data.json
{
  "id": "60d0fe4f5311236168a109dd",
  "title": "mr",
  "firstName": "Miguel",
  "lastName": "Lima",
  "picture": "https://randomuser.me/api/portraits/med/men/31.jpg",
  "gender": "male",
  "email": "miguel.lima@example.com",
  "dateOfBirth": "1979-07-05T22:21:32.623Z",
  "phone": "(33) 1399-0495",
  "location": {
    "street": "9637, Rua Rio de Janeiro ",
    "city": "Cascavel",
    "state": "AmapÃ¡",
    "country": "Brazil",
    "timezone": "+4:00"
  },
  "registerDate": "2021-06-21T21:02:10.647Z",
  "updatedDate": "2021-06-21T21:02:10.647Z"
}
